name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.2"
          cabal-version: "latest"

      - name: Cache Cabal store
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project', '**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Update package index
        run: cabal update

      - name: Install tooling
        run: cabal install --installdir=$HOME/.cabal/bin --overwrite-policy=always ormolu hlint

      - name: Ormolu formatting check
        run: |
          files=$(git ls-files '*.hs')
          if [ -n "$files" ]; then
            ormolu --mode check $files
          fi

      - name: HLint
        run: |
          files=$(git ls-files '*.hs')
          if [ -n "$files" ]; then
            hlint $files
          fi

      - name: Build
        run: cabal build all

      - name: Run tests
        run: cabal test all --test-show-details=direct

      - name: Cabal check
        run: cabal check
